### ISSUE TITLE
Use libSwiftPM instead of custom model types

### ISSUE THREAD

**Issue by MaxDesiatov** [swiftwasm/carton#120]
Instead of maintaining our own packaga manifest model types, we should consider using [the SwiftPackageManifest package](https://github.com/SwiftDocOrg/SwiftPackageManifest) to offload this burden. The package is going to be reused in [`swift-doc`](https://github.com/SwiftDocOrg/swift-doc) in the future, so this feels safe to rely on.

**Comment by yonihemi** [comment]
SwiftPackageManifest currently fails on dumps generated with Swift 5.3 due to a change in `dump-package` output, plus at least 2 features are not supported (exact versioned dependencies, dependencies as packages and not names).
I'm working on some PRs for that, but meanwhile seems our decoding approach in Carton helps us avoid these issues - the  more minimal decoding for only the parts we need proves more resilient to JSON changes.

**Comment by MaxDesiatov** [comment]
Another option could be a dependency on `SwiftPMDataModel` target in [SwiftPM itself](https://github.com/apple/swift-package-manager/blob/main/Package.swift). They say their API is unstable, but it won't break if we stick to a specific Swift version (5.3 in our case).

Then we also get access to things like `PackageGraph`, which AFAIU allows us to read `Package.resolved`. We could then run deep checks on the dependency tree to verify that JavaScriptKit is compatible with the runtime version that `carton` ships with. Right now we can only fetch JavaScriptKit version from `Package.swift`, but it's not there if you don't depend on it directly.
